# -*- coding: utf-8 -*-
"""Subjectivity Classiifier- Clef.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YguaDz6z-e3qWcZbNJW_VauzbQ7aW3D
"""

pip install datasets

"""Imports

"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from transformers import BertTokenizer, BertForSequenceClassification
from transformers import Trainer, TrainingArguments
import torch
from torch.utils.data import DataLoader

from datasets import Dataset

from sklearn.metrics import classification_report,confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

"""load dataset"""

# Load the data (TSV = tab-separated values)
langs = ['ar', 'bg', 'de', 'en', 'it']
dfs = []

for lang in langs:
    # Use f-string formatting to correctly insert the 'lang' value into the filename
    df = pd.read_csv(f"/content/train_{lang}.tsv", sep="\t")
    df['lang'] = lang
    dfs.append(df)

data = pd.concat(dfs, ignore_index=True)

# # Only drop 'Unnamed: 0' if it exists
# if 'Unnamed: 0' in data.columns:
#     data = data.drop(columns=['Unnamed: 0'])

# # Drop any rows with missing values
# data.dropna(inplace=True)

# Display the dataframe
data

data = data.sample(n=2500, random_state=42).reset_index(drop=True)
data

"""preprocessing"""

import re
import nltk
from nltk.corpus import stopwords

# Download necessary NLTK resources
nltk.download('stopwords')

# Manually define Bulgarian stopwords
bulgarian_stopwords = {
    'аз', 'ако', 'ала', 'без', 'беше', 'би', 'бил', 'била', 'били', 'било', 'бих',
    'биха', 'бихме', 'бихте', 'бяха', 'бъдат', 'бъде', 'бъдем', 'бъдете', 'бъдейки', 'бъда',
    'в', 'вас', 'ваш', 'ваша', 'ваше', 'ваши', 'вие', 'във', 'въпреки', 'върху', 'ги', 'го', 'гова',
    'дали', 'да', 'до', 'дори', 'друг', 'друга', 'други', 'друго', 'е', 'евентуално', 'едва', 'едва ли',
    'един', 'една', 'едно', 'едни', 'ето', 'за', 'зад', 'заедно', 'защо', 'защото', 'и', 'из', 'или',
    'им', 'има', 'имат', 'иска', 'искат', 'как', 'какво', 'както', 'като', 'кога', 'когато', 'кой',
    'който', 'която', 'кое', 'кои', 'къде', 'където', 'ли', 'малко', 'ме', 'между', 'мен', 'ми', 'миналия',
    'мина', 'много', 'могат', 'може', 'можеше', 'моето', 'мой', 'моя', 'моята', 'му', 'н', 'на',
    'над', 'най', 'накрая', 'нам', 'нас', 'не', 'него', 'ней', 'нея', 'неща', 'ни', 'ние', 'ним',
    'них', 'но', 'обаче', 'от', 'отгоре', 'относно', 'по', 'под', 'покрай', 'поне', 'поради', 'после',
    'пред', 'преди', 'през', 'при', 'против', 'пък', 'сам', 'сама', 'сами', 'само', 'самата', 'самото',
    'се', 'сега', 'си', 'скоро', 'след', 'сме', 'смях', 'съм', 'със', 'също', 'същият', 'същата', 'същото',
    'съществува', 'та', 'тази', 'така', 'такъв', 'там', 'те', 'теб', 'тебе', 'тези', 'ти', 'това', 'тогава',
    'той', 'толкова', 'този', 'то', 'точно', 'трябва', 'тя', 'тях', 'у', 'хубаво', 'чрез', 'че', 'често',
    'ще', 'щом', 'я'
}

# Map language codes to their stopwords
stopword_map = {
    'ar': set(stopwords.words('arabic')),
    'bg': bulgarian_stopwords,  # use manual stopwords for Bulgarian
    'de': set(stopwords.words('german')),
    'en': set(stopwords.words('english')),
    'it': set(stopwords.words('italian')),
}

# Function to clean a single statement
def clean_statement(statement, lang):
    if not isinstance(statement, str):
        return statement  # In case some value is NaN or not a string

    # Lowercase
    statement = statement.lower()

    # Remove special characters and numbers
    statement = re.sub(r'[^\w\s]', '', statement)
    statement = re.sub(r'\d+', '', statement)

    # Tokenize and remove stopwords
    words = statement.split()
    stop_words = stopword_map.get(lang, set())
    words = [word for word in words if word not in stop_words]

    # Rejoin
    return ' '.join(words)

# Apply the cleaning function
data['sentence'] = data.apply(lambda row: clean_statement(row['sentence'], row['lang']), axis=1)

data

"""BALANCE DATASETS"""

data['label'].value_counts()

from imblearn.over_sampling import RandomOverSampler
import pandas as pd

# Create an instance of RandomOverSampler
ros = RandomOverSampler(sampling_strategy='auto', random_state=42)

# Define features (X) and target (y)
X = data.drop(columns=['label'])  # Change 'status' → 'label'
y = data['label']

# Perform oversampling
X_resampled, y_resampled = ros.fit_resample(X, y)

# Combine the oversampled features and target back into a DataFrame
data = pd.concat([X_resampled, y_resampled], axis=1)

# Check the new class distribution
print(data['label'].value_counts())

# Label encoding for 'status' column
label_encoder = LabelEncoder()
data['label'] = label_encoder.fit_transform(data['label'])

from sklearn.model_selection import train_test_split

train_texts, test_texts, train_labels, test_labels = train_test_split(
    data['sentence'], data['label'], test_size=0.2, random_state=42
)

max([len(text) for text in data['sentence']])

from transformers import BertTokenizer

# Load tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

# Tokenize the train and test texts
train_encodings = tokenizer(list(train_texts), padding=True, truncation=True, max_length=200)
test_encodings = tokenizer(list(test_texts), padding=True, truncation=True, max_length=200)

from datasets import Dataset

# Convert to Hugging Face Dataset format
train_dataset = Dataset.from_dict({
    'input_ids': train_encodings['input_ids'],
    'attention_mask': train_encodings['attention_mask'],
    'labels': train_labels.tolist()
})

test_dataset = Dataset.from_dict({
    'input_ids': test_encodings['input_ids'],
    'attention_mask': test_encodings['attention_mask'],
    'labels': test_labels.tolist()
})

pip install torch

pip install huggingface_hub[hf_xet]

from transformers import BertForSequenceClassification

model = BertForSequenceClassification.from_pretrained(
    "bert-base-multilingual-cased",
    num_labels=len(label_encoder.classes_)
)

from transformers import BertForSequenceClassification, Trainer, TrainingArguments

import os

# 🚫 Disable W&B logging
os.environ["WANDB_DISABLED"] = "true"

# 🧠 Load model
model = BertForSequenceClassification.from_pretrained(
    "bert-base-multilingual-cased",
    num_labels=len(label_encoder.classes_)
)

# ⚙️ Set training arguments
training_args = TrainingArguments(
    output_dir="./results",              # Output directory for results
    eval_strategy="epoch",               # ✅ updated to avoid deprecation
    save_strategy="epoch",               # Save model at end of each epoch
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=7,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    lr_scheduler_type="linear",
    warmup_steps=500,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    save_total_limit=3,
    gradient_accumulation_steps=2
)

# 🏋️ Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

# 🚀 Train the model
trainer.train()



# 📊 1. Make predictions
predictions, labels, _ = trainer.predict(test_dataset)

# 🎯 2. Convert logits to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

# 🧾 3. Classification Report
print("Classification Report:")
print(classification_report(test_labels, predicted_labels, target_names=label_encoder.classes_))

# 🔀 4. Confusion Matrix
cm = confusion_matrix(test_labels, predicted_labels)

plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)

plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# ✅ Save model & tokenizer
trainer.save_model("saved_subjectivity_Classifier_bert")           # Save fine-tuned BERT model
tokenizer.save_pretrained("saved_subjectivity_Classifier_bert")    # Save tokenizer

# ✅ Save LabelEncoder
import pickle
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)

from transformers import AutoModelForSequenceClassification, AutoTokenizer
import pickle

# Load the model and tokenizer from the saved directory
model = AutoModelForSequenceClassification.from_pretrained("saved_subjectivity_Classifier_bert")
tokenizer = AutoTokenizer.from_pretrained("saved_subjectivity_Classifier_bert")

# Load the LabelEncoder
with open('label_encoder.pkl', 'rb') as f:
    label_encoder = pickle.load(f)

import torch

# 🧼 1. Detection Function
def detect_label(text, lang):
    # Clean the input
    cleaned_text = clean_statement(text, lang)

    # Tokenize the input
    inputs = tokenizer(
        cleaned_text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=512
    )

    # Run the model
    with torch.no_grad():
        outputs = model(**inputs)

    # Get predicted class
    logits = outputs.logits
    predicted_class = torch.argmax(logits, dim=1).item()

    # Decode predicted label
    return label_encoder.inverse_transform([predicted_class])[0]

# 🧪 2. Sample Texts with Language
sample_texts = [
    ("أشعر أن المدينة أصبحت أكثر ازدحامًا مما كانت عليه.", 'ar'),
    ("تأسست شركة أرامكو السعودية عام 1933.", 'ar'),
    ("بصراحة، أعتقد أن هذا الحي هو الأجمل في الرياض.", 'ar'),
    ("أعلنت الحكومة رفع أسعار الكهرباء بنسبة 10٪.", 'ar'),
    ("في رأيي، يجب تحسين وسائل النقل العام.", 'ar'),
    ("انتهى مشروع توسعة المطار خلال عام 2022.", 'ar'),
    ("أظن أن هذا الفريق لديه فرصة كبيرة للفوز.", 'ar'),
    ("عدد سكان المملكة بلغ 36 مليون نسمة عام 2024.", 'ar'),
    ("أحببت طريقة تقديم المحاضرة بشكل بسيط وواضح.", 'ar'),
    ("هطلت أمطار غزيرة على جدة الأسبوع الماضي.", 'ar'),

    ("Credo che questa sia stata la scelta migliore.", 'it'),
    ("Il museo nazionale è stato fondato nel 1865.", 'it'),
    ("Secondo me, il nuovo ristorante offre piatti deliziosi.", 'it'),
    ("La temperatura a Roma oggi è di 27 gradi.", 'it'),
    ("Penso che dovrebbero migliorare il servizio clienti.", 'it'),
    ("L'azienda ha registrato una crescita del 12% quest'anno.", 'it'),
    ("A mio avviso, il film era troppo lungo e noioso.", 'it'),
    ("Il treno delle 10:00 per Milano è stato cancellato.", 'it'),
    ("Mi sembra che questa decisione sia affrettata.", 'it'),
    ("Il concerto inizia alle 20:30 al teatro centrale.", 'it'),

    ("Мисля, че този проект ще има голям успех.", 'bg'),
    ("Министерството на здравеопазването обяви нова кампания.", 'bg'),
    ("От моя гледна точка, мерките са прекалено строги.", 'bg'),
    ("Температурите ще достигнат 35 градуса тази седмица.", 'bg'),
    ("Вярвам, че можем да постигнем още повече.", 'bg'),
    ("Новият мост ще бъде завършен до края на годината.", 'bg'),
    ("Смятам, че трябва да се инвестира повече в образованието.", 'bg'),
    ("НАСА планира нова мисия към Марс през 2026 година.", 'bg'),
    ("Честно казано, това е най-добрият отбор, който съм виждал.", 'bg'),
    ("България ще бъде домакин на международен форум тази есен.", 'bg'),

    ("I honestly believe this city is the best in the country.", 'en'),
    ("The bridge collapsed during a storm last year.", 'en'),
    ("In my opinion, the new rules are too strict.", 'en'),
    ("The hospital admitted over 300 patients last week.", 'en'),
    ("I feel this movie deserved more awards.", 'en'),
    ("The team won the championship by 5 points.", 'en'),
    ("It's clear to me that the project is a failure.", 'en'),
    ("The company reported a 7% increase in profits.", 'en'),
    ("I absolutely loved the performance last night.", 'en'),
    ("The annual conference will be held in Chicago this year.", 'en'),

    ("Meiner Meinung nach ist dieses Buch wirklich inspirierend.", 'de'),
    ("Das Museum wurde im Jahr 1902 eröffnet.", 'de'),
    ("Ich finde, dass die neuen Regeln unfair sind.", 'de'),
    ("Die Temperaturen erreichten gestern 30 Grad Celsius.", 'de'),
    ("Ich glaube, dass wir mehr in Bildung investieren sollten.", 'de'),
    ("Das Unternehmen eröffnete eine neue Filiale in Hamburg.", 'de'),
    ("Aus meiner Sicht war das Konzert ein voller Erfolg.", 'de'),
    ("Die Bahnstrecke wurde wegen Wartungsarbeiten gesperrt.", 'de'),
    ("Ich denke, der neue Film ist absolut sehenswert.", 'de'),
    ("Die Stadtbibliothek wird im nächsten Monat renoviert.", 'de')
]

# 🔍 3. Run detection
for text, lang in sample_texts:
    predicted_class = detect_label(text, lang)
    print(f"📝 Sentence: {text}\n➡️ Predicted Label: {predicted_class}\n")

import pandas as pd
import torch
import zipfile
# import re
# import nltk
# from nltk.corpus import stopwords

# 🧼 1. Detection Function



# # Download NLTK stopwords
# nltk.download('stopwords')

# # Get English stopwords from NLTK
# stop_words = set(stopwords.words('romanian'))

# def clean_statement(statement):
#     # Convert to lowercase
#     statement = statement.lower()

#     # Remove special characters (punctuation, non-alphabetic characters)
#     statement = re.sub(r'[^\w\s]', '', statement)

#     # Remove numbers
#     statement = re.sub(r'\d+', '', statement)

#     # Tokenize and remove stopwords
#     words = statement.split()
#     words = [word for word in words if word not in stop_words]

#     # Rejoin into a cleaned statement
#     cleaned_statement = ' '.join(words)
#     return cleaned_statement

# Apply to the correct column: 'sentence'


def detect_label(text):
    # cleaned_text = clean_statement(text)

    inputs = tokenizer(
        text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=512
    )

    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits
    predicted_class = torch.argmax(logits, dim=1).item()

    return label_encoder.inverse_transform([predicted_class])[0]

# 📂 2. Load the input TSV file
input_file = "/content/test_pol_unlabeled.tsv"
df = pd.read_csv(input_file, sep="\t")

assert 'sentence_id' in df.columns and 'sentence' in df.columns, "Input file must have 'sentence_id' and 'sentence' columns"

# 🔍 3. Predict labels and keep alignment
labels = df['sentence'].map(detect_label)  # map() keeps index alignment

# Combine sentence_id + label
output_df = pd.DataFrame({
    'sentence_id': df['sentence_id'],
    'label': labels
})

# 💾 4. Save the TSV output
tsv_output_path = "/content/task1_test_pol.tsv"
output_df.to_csv(tsv_output_path, sep="\t", index=False)

# 🗜️ 5. Zip the TSV file
zip_output_path = "/content/task1_test_pol.zip"
with zipfile.ZipFile(zip_output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    zipf.write(tsv_output_path, arcname="task1_test_pol.tsv")

print(f"✅ TSV saved to: {tsv_output_path}")
print(f"✅ ZIP file created: {zip_output_path}")